version: '3.8'
services:
  api:
    build: .
    image: api:v9
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/muralvagas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muralvagas
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:







